export const serviceKeywords: Record<string, string[]> = {
    nails: [
        "nail salon",
        "nails",
        "manicure",
        "pedicure",
        "nail enhancements",
        "nail shaping",
        "cuticle care",
        "herbal detox pedicure",
        "acrylic nails",
        "woman pedicure",
        "builder gel",
        "man pedicure",
    ],
    browns: [
        "eyebrows",
        "eyebrow tattoo",
        "powder brows",
        "semi-permanent makeup",
        "brow shaping",
        "architectural brow design",
        "brow tattoo",
        "powders browns",
    ],
    lashes: [
        "lash extensions",
        "eyelash extensions",
        "classic set",
        "hybrid lashes",
        "volume lashes",
        "lash lift",
        "lash refill",
        "lifting",
        "dramatic lashes",
        "wispy lashes",
        "hawaiian"
    ],
    "facial-tr": [
        "facial treatments",
        "skin revival therapies",
        "microneedling",
        "mironeedling treatment",
        "oxygen facial",
        "hydrogen oxygen facial",
        "high frequency facial",
        "high frecuency treatment",
        "led light therapy",
        "led lights treatment",
        "acne facial",
        "anti-aging facial",
    ],
    "facial-hr": [
        "laser hair removal",
        "facial hair removal",
        "upper lip hair removal",
        "chin hair removal",
        "sideburns hair removal",
        "full face hair removal",
        "full face",
        "neck (front or back)",
        "sideburns",
        "chin",
        "upper lip",
    ],
    "upper-hr": [
        "laser hair removal",
        "upper body hair removal",
        "underarms",
        "full arms",
        "half arms",
        "chest",
        "abdomen",
        "shoulders",
        "hands & fingers",
        "hands and fingers",
        "full back",
    ],
    "lower-hr": [
        "laser hair removal",
        "lower body hair removal",
        "full legs",
        "half legs",
        "brazilian",
        "bikini line",
        "buttocks",
        "feet and toes",
    ],
    "full-hr": [
        "laser hair removal",
        "full body laser hair removal",
        "full body",
        "upper body combo",
        "lower body combo",
        "hair removal packages",
    ],
};
